apiVersion: v2
name: sonarr
description: A Helm chart for deploying Sonarr
type: application
version: 2.0.2
appVersion: "4.0.6"
maintainers:
  - name: WojoInc
    email: wojoinc@pm.me
dependencies:
  - name: common
    version: 0.4.2
    repository: oci://registry.gitlab.com/wojoinc/helm-charts
