apiVersion: v2
name: sonarr
description: A Helm chart for deploying Sonarr
type: application
version: 1.0.2
appVersion: "3.0.10"

dependencies:
  - name: common
    version: 0.4.2
    repository: oci://registry.gitlab.com/wojoinc/helm-charts
