nameOverride: ""

services:
  main:
    enabled: true
    ports:
      - name: http
        port: 6767
        target: http

deployments:
  main:
    enabled: true
    context:
      fsGroup: 568
      gid: 568
      uid: 568
      extraGids:
        - 997
    containers:
      main:
        env:
          - name: TZ
            value: America/Chicago
        image:
          repository: ghcr.io/onedr0p/bazarr
        resources:
          limits:
            cpu: "1"
            memory: 1024Mi
          requests:
            cpu: 25m
            memory: 100Mi
        ports:
          http:
            port: 6767
        probes:
          liveness:
            enabled: true
            port: 6767
          readiness:
            enabled: true
            port: 6767
          startup:
            enabled: true
            port: 6767
