service:
  port: 7878
image:
  repository: ghcr.io/onedr0p/radarr
  tag: 5.19.3
ingress:
  main:
    enabled: true
    className: "traefik-external"
    host: "radarr.wojoinc.xyz"
    tls: true
    annotations:
      cert-manager.io/cluster-issuer: acme
      dns.homelab.wojoinc.xyz/publish-external: "true"
      external-dns.alpha.kubernetes.io/target: wojoinc.xyz.
      traefik.ingress.kubernetes.io/router.middlewares: media-forward-auth-all@kubernetescrd,media-forward-auth@kubernetescrd
  api:
    enabled: true
    className: "traefik-external"
    host: "radarr.wojoinc.xyz"
    path: "/api"
    tls: true
    annotations:
      cert-manager.io/cluster-issuer: acme
      dns.homelab.wojoinc.xyz/publish-external: "true"
      external-dns.alpha.kubernetes.io/target: wojoinc.xyz.
persistence:
  config:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: "5Gi"
    className: "openebs-quicktank-localpv"
  media:
    existingClaim: "media-local"
    enabled: true
probes:
  livenessCmd:
    - /usr/bin/env
    - bash
    - -c
    # yamllint disable rule:line-length
    - curl --fail localhost:7878/api/v3/system/status?apiKey=`IFS=\> && while read -d
      \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`