apiVersion: v2
name: lidarr
description: A Helm chart for deploying lidarr
type: application
version: 1.0.0
appVersion: "1.4.5"
maintainers:
  - name: WojoInc
    email: wojoinc@pm.me
dependencies:
  - name: common
    version: 0.4.2
    repository: oci://registry.gitlab.com/wojoinc/helm-charts
