nameOverride: ""

services:
  main:
    enabled: true
    ports:
      - name: http
        port: 8787
        target: http

deployments:
  main:
    enabled: true
    context:
      fsGroup: 568
      gid: 568
      uid: 568
      extraGids:
        - 995
    containers:
      main:
        env:
          - name: TZ
            value: America/Chicago
        image:
          repository: ghcr.io/onedr0p/readarr-develop
        resources:
          limits:
            cpu: "1"
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
          http:
            port: 8787
        probes:
          liveness:
            enabled: true
            port: 8787
          readiness:
            enabled: true
            port: 8787
          startup:
            enabled: true
            port: 8787
