{{- /*
bookstack.resourceName sets the name of a resource based on the chart and release name, and optionally, a
manually specified resource name to be appended to the generated name.
In the event the release and chart names are the same, it will simply use the release name to
avoid ugly names generated by simply combining the two.
If extraResourceName == "main", it will be ignored
*/}}
{{- define "bookstack.resourceName" -}}
{{- $ctx := .ctx -}}
{{- $extraResourceName := .extraResourceName -}}
{{- if ne $ctx.Values.nameOverride ""}}
  {{- eq $extraResourceName "main" | ternary ($ctx.Values.nameOverride) ($extraResourceName | printf "%s-%s" $ctx.Values.nameOverride) -}}
{{- else -}}
  {{- eq $extraResourceName "main" | ternary ($ctx.Release.Name) ($extraResourceName | printf "%s-%s" $ctx.Release.Name) -}}
{{- end -}}
{{- end -}}
