nameOverride: ""

services:
  main:
    enabled: true
    ports:
      - name: http
        port: 8083
        target: http

deployments:
  main:
    enabled: true
    context:
      fsGroup: 568
      gid: 568
      uid: 568
    containers:
      main:
        env:
          - name: DOCKER_MODS
            value: ghcr.io/linuxserver/mods:universal-calibre
          - name: PGID
            value: "568"
          - name: PUID
            value: "568"
          - name: TZ
            value: America/Chicago
        image:
          repository: ghcr.io/linuxserver/calibre-web
        resources:
          limits:
            cpu: 1500m
            memory: 1532Mi
          requests:
            cpu: 200m
            memory: 100Mi
        ports:
          http:
            port: 8083
        probes:
          liveness:
            enabled: true
            port: 8083
          readiness:
            enabled: true
            port: 8083
          startup:
            enabled: true
            port: 8083
