{{/*
common.util.security.podContext templates the security context for a deployment based on provided values.
*/}}
{{- define "common.security.podContext" -}}
{{- if not (empty $.fsGroup) -}}
fsGroup: {{ $.fsGroup }}
{{- end }}
{{- if not (empty $.gid) }}
runAsGroup: {{ $.gid }}
{{- end }}
{{- if not (empty $.uid) }}
runAsUser: {{ $.uid }}
{{- end }}
{{- if not (empty $.extraGids) }}
supplementalGroups: {{ $.extraGids | toYaml | nindent 2 }}
{{- end }}
{{- end -}}

{{/*
common.util.security.podContext templates the security context for a deployment based on provided values.
*/}}
{{- define "common.security.containerContext" -}}
allowPrivilegeEscalation: {{ .allowPrivilegeEscalation | default false }}
{{ if not (empty .capabilities) }}
capabilities: {{ .capabilites | toYaml | nindent 2 }}
{{- else -}}
capabilities:
  drop:
    - ALL
{{- end }}
readOnlyRootFilesystem: {{ .readOnlyRoot | default false}}
{{- end -}}