deployments:
  main:
    volumes:
      config:
        type: emptyDir
    containers:
      main:
        volumeMounts:
          config:
            path: "/config"
        env:
          - name: DATA_FOLDER
            value: config
          - name: DOMAIN
            value: https://bw.wojoinc.xyz
          - name: ROCKET_PORT
            value: "1080"
          - name: TZ
            value: America/Chicago
