{{- define "common.resource.ingress" -}}
{{- range $key, $ingress := .Values.ingresses }}
  {{- /* Check if ingress should be enabled */ -}}
  {{- $ingressEnabled := false -}}
  {{- if hasKey $ingress "enabled" -}}
    {{- $ingressEnabled = $ingress.enabled -}}
  {{- end -}}
  {{- if $ingressEnabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.util.resourceName" (dict "rootCtx" $ "extraResourceName" $key) }}
  labels: {{ include "common.util.metadata.labels" $ | nindent 4}}
  annotations: {{empty .annotations | ternary (`{}`) (.annotations | toYaml | nindent 4) }}
spec:
  ingressClassName: {{ .className | quote }}
  tls: {{ .tls | toYaml | nindent 4 }}
  rules: {{- range $rule := .rules}}
    - host: {{ .host | quote }}
      http:
        paths: {{- range $path := .paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType }}
            backend: {{ .backend | toYaml | nindent 14}}
          {{- end -}}
  {{ end }}
{{ end }}
{{- end -}}
{{- end -}}
