{{- define "common.resource.service" -}}
{{- range $key, $service := .Values.services }}
  {{- /* Check if service should be enabled */ -}}
  {{- $serviceEnabled := false -}}
  {{- if hasKey $service "enabled" -}}
    {{- $serviceEnabled = $service.enabled -}}
  {{- end -}}
  {{- if $serviceEnabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.util.resourceName" (dict "rootCtx" $ "extraResourceName" $key) }}
  labels: {{ include "common.util.metadata.labels" $ | nindent 4}}
  annotations: {{empty $service.annotations | ternary (`{}`) ($service.annotations | toYaml | nindent 4) }}
spec:
  type: {{ $service.type | default "ClusterIP"}}
  {{- if eq $service.type "Loadbalancer" }}
  loadBalancerIP: {{ required "loadBalancerIP is required when .type == Loadbalancer" $service.loadBalancerIP }}
  {{- end -}}
  {{- if $service.trafficPolicy }}
  externalTrafficPolicy: {{ $service.trafficPolicy.external | default "Cluster" }}
  internalTrafficPolicy: {{ $service.trafficPolicy.internal | default "Cluster" }}
  {{- end -}}
  ports:
    {{- range $port := $service.ports}}
    - port: {{ $port.port }}
      targetPort: {{ $port.target }}
      protocol: {{ $port.protocol | default "TCP" }}
      name: {{ $port.name }}
    {{- end }}
  selector: {{ include "common.util.metadata.selectorLabels" $ | nindent 4 }}
{{ end }}
{{- end -}}
{{- end -}}
