{{- define "common.resource.service" -}}
{{- range $key, $service := .Values.services }}
  {{- /* Check if service should be enabled */ -}}
  {{- $serviceEnabled := false -}}
  {{- if hasKey $service "enabled" -}}
    {{- $serviceEnabled = $service.enabled -}}
  {{- end -}}
  {{- if $serviceEnabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.util.resourceName" (dict "rootCtx" $ "extraResourceName" $key) }}
spec:
  type: {{ $service.type | default "ClusterIP"}}
  ports:
    {{- range $port := $service.ports}}
    - port: {{ $port.port }}
      targetPort: {{ $port.target }}
      protocol: {{ $port.protocol | default "TCP" }}
      name: {{ $port.name }}
    {{- end }}
{{- end }}
{{- end -}}
{{- end -}}
