{{- define "common.resource.service" -}}
{{- range $key, $service := .Values.services }}
  {{- /* Check if service should be enabled */ -}}
  {{- $serviceEnabled := false -}}
  {{- if hasKey $service "enabled" -}}
    {{- $serviceEnabled = $service.enabled -}}
  {{- end -}}
  {{- if $serviceEnabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.util.resourceName" (dict "rootCtx" $ "extraResourceName" $key) }}
spec:

{{- end }}
{{- end -}}
{{- end -}}
