---
name: Release Charts
on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
permissions:
  contents: write
  packages: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: '0'
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112
        with:
          version: v3.18.5
      - name: Build chart dependencies
        run: |
          for dir in charts/*/
          do
            cd ${dir}; helm dependency build
          done
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f
        with:
          version: v1.8.1
        env:
          CR_GENERATE_RELEASE_NOTES: true
          CR_SKIP_EXISTING: true
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Login to GitHub Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login -u ${{ github.actor }} --password-stdin ghcr.io
      - name: Push Charts to GHCR
        run: .github/helm-push.sh ${{ github.repository }}
